# Numpy-1
7월 20일

In [1]:
import numpy
numpy.__version__
import numpy as np

### 파이썬의 데이터 타입 이해하기  
데이터 배열이 어떻게 처리되는지 간단히 설명 및 비교  

**동적타이핑**  
정적타입체계를 가진 언어는 모든 변수를 명시적으로 선언해야하지만, 동적타입체계를 가진 언어는 타입을 지정하지 않아도 된다.   
모든 변수에 어떤 종류의 데이터든 할당할 수 있다.  

파이썬 리스트는 여러 개의 요소를 담을 수 있지만 이 유연성에는 비용이 따른다. 리스트의 각 항목에 타입정보, 참조 횟수, 기타 정보가 들어가야한다. 

In [4]:
L=list(range(10))
print(L)
print(type(L[0]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'int'>


In [6]:
L2=[str(c) for c in L]
print(L2)
print(type(L2[0]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'str'>


In [7]:
L3=[True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### 파이썬의 고정 타입 배열

array 모듈을 사용할 수도 있지만 numpy의 ndarray가 더 유용하다.  
**NumPy는 배열의 모든 요소가 같은 타입이어야 한다.**  
타입이 일치하지 않으면 가능한 경우 상위 타입을 취하게 된다.

In [9]:
np.array([1,4,2,5,3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [10]:
# 리스트를 중첩하면 다차원 배열이 된다. 

np.array([range(i, i+3) for i in [2,6,4]])

array([[2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

### 처음부터 배열 만들기 

In [14]:
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# 1로 채운 3*5 부동소수점 배열 만들기  
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# 3.14로 채운 3*5 배열 만들기  
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# 0에서 시작해 2씩 더해 20까지 채움
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# 0과 1사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 3*3 배열, 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.36546671, 0.93841652, 0.96614843],
       [0.52826517, 0.95693519, 0.78417722],
       [0.90572519, 0.3599557 , 0.88010874]])

In [21]:
# 정규 분포(평균=0, 표준편차=1)의 난수로 채운 3*3 배열
np.random.normal(0,1,(3,3))

array([[ 2.45743804, -0.24727606, -1.10248475],
       [-1.03088142,  1.61422417,  0.28090672],
       [ 1.05460854,  0.04287723, -0.03069134]])

In [22]:
#[0,10] 구간의 임의의 정수로 채운 3*3 배열
np.random.randint(0,10,(3,3))

array([[7, 3, 7],
       [6, 4, 4],
       [6, 6, 1]])

In [24]:
# 3*3 단위 행렬 만들기
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기  
np.empty(3)

array([1., 1., 1.])

### NumPy 배열 속성 지정

In [29]:
# 재현 가능성을 위한 시드 값
np.random.seed(0)

x1=np.random.randint(10, size=6)
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5))

print('x3 ndim:', x3.ndim)  # 차원의 개수
print('x3 shape:', x3.shape) # 각 차원의 크기
print('x3 size:', x3.size) # 전체 배열의 크기
print('x3 dtype:', x3.dtype) # 타입

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


### 배열 인덱싱, 단일 요소에 접근하기

In [31]:
print(x1)
print(x1[0])
print(x1[3])

[5 0 3 3 7 9]
5
3


In [33]:
# 배열을 끝에서부터 인덱싱하려면 음수 인덱스
x1[-2]

7

In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[0,0]

3

In [37]:
x2[2,3]

7

In [39]:
x2[2,-3]

6

In [41]:
# 값 수정
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### 배열 슬라이싱: 하위 배열에 접근하기

**1차원**

In [42]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x[:5]

array([0, 1, 2, 3, 4])

In [44]:
# 하나 걸러 하나씩의 요소로 구성된 배열  
x[::2]

array([0, 2, 4, 6, 8])

In [45]:
# 인덱스 1부터 시작해 하나 걸러 하나씩 요소로 구성된 배열
x[1::2]

array([1, 3, 5, 7, 9])

In [46]:
## 모든 요소를 거꾸로 나열
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
# 인덱스 5부터 하나 걸러 하나씩 요소를 거꾸로 나열
x[5::-2]

array([5, 3, 1])

**다차원**

In [49]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
# 두 개의 행, 세 개의 열
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [53]:
# 모든 행, 한 열 걸러 하나씩
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [54]:
# 역으로 변환
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [55]:
# 첫번째 열
x2[:,0]

array([12,  7,  1])

In [56]:
# 첫번째 행
x2[0,:]

array([12,  5,  2,  4])

In [57]:
# 행에 접근하는 경우 더 간단하게는
print(x2[0])

[12  5  2  4]


**사본**

In [58]:
x2_sub_copy=x2[:2,:2].copy()

In [59]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
